CSCI-GA-2820-SP23-003/inventory

.devcontainer/devcontainer.json

Made changes to devcontainer.json. Tested on local machine to see if it doesn't break anything.

Changes made to devcontainer.json to fix vscode bug

---

service/models.py
service/routes.py
tests/factories.py
tests/test_models.py

- Designed and created a table for inventory items
- Added unittests
- Added `tests/fixtures/inventory_item_names.csv` to choose random inventory item names for Factory

Added Database model for Inventory items

---

service/models.py
tests/factories.py
tests/test_models.py

- fix serialize and deserialize functions to correctly handle enum Condition

Fixed JSON Serializable error for enum Condition

---

service/routes.py
tests/test_routes.py

- Added support for the Create endpoint.
- Added relevant happy and sad path tests.

Added Create endpoint for Inventory.

---

service/routes.py
tests/test_routes.py

- Added endpoint to read-inventory in `routes.py`
- Added test cases for read-inventory

Add Read inventory

---

README.md
service/routes.py
tests/test_routes.py

- Added update inventory code.
- Added three unit tests for updating inventory
- Updated README

Update inventory route

---

README.md
service/routes.py
tests/test_routes.py

Endpoint to delete inventory item based on ID

Delete inventory item

---

service/routes.py
tests/test_routes.py

- Update `index()` for root URL response in `routes.py`
- Add test cases for root URL response
- Add `location_url` in create-inventory
- Add corresponding test cases for `location_url` for create-inventory
nosetests passed

Root url response

---

README.md
service/common/error_handlers.py
service/common/log_handlers.py
service/routes.py
tests/test_models.py
tests/test_routes.py

- Added an endpoint to list all inventory items
- Added tests for bad condition while creating an item and method not supported
- Removed error handling for HTTP 409 Conflict
- Fixed pylint warnings
- Updated root URL to include list endpoint
- Updated README

Added list inventory items endpoint

---

.github/workflows/tdd.yml
service/models.py
service/routes.py
setup.cfg
tests/factories.py
tests/test_models.py
tests/test_routes.py

- Added TDD yaml files
- Added support for codecov

Added TDD yaml

---

service/models.py
tests/test_models.py

- Added a function to query Inventory items by condition
- Supports strings and enums
- Added tests

Added query by condition capability to Inventory Model

---

README.md

- Updated `README` with the Github Actions badge for Build

Added Actions badge

---

README.md

Updated Readme with DB schema

---

.devcontainer/docker-compose.yml
.devcontainer/scripts/install-tools.sh

- Modify `docker-compose.yml`: copy ~/.inventory/apikey.json to the container
- Modify `.devcontainer/scripts/install-tools.sh` to install **container-service** and install platform specific installs

UPDATE: docker-compose file and install-tools file

---

Makefile

- Name of k8s cluster was incorrect.

Bug in k8s cluster name

---

Dockerfile
Makefile
deploy/deployment.yaml
deploy/postgresql.yaml
deploy/service.yaml

Pods and service running on default namespace. I see a story to deploy on dev and prod so tested it out on default.

kubectl metadata files created

---

service/routes.py
tests/test_routes.py

Fix typo in usage information of root url response

FIX: typo in root url response

---

service/models.py
service/routes.py
tests/factories.py
tests/test_models.py
tests/test_routes.py

- added query to list items that need to or don't need to be restocked
- updated value range for `restock_level` in `factories.py`

Added Query for Items that need Restocking

---

service/routes.py
tests/test_routes.py

Added query by name

---

service/routes.py
service/static/index.html
service/static/js/rest_api.js

- Added restock button to UI
- Fixed abort messages in restock function of `routes.py`

Added Restock Button to UI

---

service/routes.py
service/static/js/rest_api.js

- Added update inventory item functionality through UI
- Updated `f-strings` in abort message

Update Inventory Item through UI

---

service/models.py
service/static/index.html
service/static/js/rest_api.js
tests/test_models.py
tests/test_routes.py

- Updated Condition dropdown on UI homepage
- Added query functionality to UI
- Added clear form functionality
- Removed time fields from query results
- Update accepted restock query string values
- Display hint when hovering over search button

Added Query Capability to UI

---

features/inventory.feature

- Add BDD scenario for listing all inventory items
- Add BDD scenario for not listing items which are not present

Add BDD for List all Inventory Items

---

features/inventory.feature
service/static/js/rest_api.js

- Add BDD scenario for creating an inventory item
- This added BDD scenario also tests the behavior of Clear button

Add BDD for Create an Inventory Item

---

features/inventory.feature

- Added a BDD scenario for updating an inventory item

Add BDD for Update an Inventory Item

---

features/inventory.feature
service/static/index.html
service/static/js/rest_api.js

- Add a ref link as a button (`API docs`) in the home page.
- Add BDD feature to test the button is working properly, run `behave` to test it.
First time coding in html and js, please let me know if there is anything incorrect.

Api docs link UI

---

service/routes.py

- Restrict ID type to int for READ, UPDATE, DELETE, RESTOCK
- Use flask-restx convention (api.payload instead of request.json)
- Change restock query string description

Update ID type to Integer in routes and model

---

service/models.py
tests/test_models.py
tests/test_routes.py

Fixed the bug that allowed items with empty names to be created. Also added tests for the same.

Fixed empty name bug
